//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Galatee.Entity.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABO07Entities : DbContext
    {
        public ABO07Entities()
            : base("name=ABO07Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CENTFAC> CENTFAC { get; set; }
        public DbSet<CPROFAC> CPROFAC { get; set; }
        public DbSet<CREDFAC> CREDFAC { get; set; }
    }
}
